Fix pinnings for ppc64le with enabled CUDA
Following the merge of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7660, the rerender of my recipe fails with:

```
ValueError: Variant configuration errors in /home/fs/.cache/conda-smithy/conda_build_config.yaml:
  zip fields in zip_key group frozenset({'cuda_compiler_version', 'c_stdlib_version', 'cxx_compiler_version', 'fortran_compiler_version', 'c_compiler_version'}) are not all the same length
```

This is due to having two output packages, one without CUDA support but built for all platforms including ppc64le, and one with CUDA support but restricted to `linux_64` and `linux_aarch64`.
With the current pinning, for the `linux_ppc64le` platform, the resulting pinnings are:

```yaml
c_compiler_version:            # [unix]
  - 14                         # [linux]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 2.17                       # [linux and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
cxx_compiler_version:          # [unix]
  - 14                         # [linux]
fortran_compiler_version:      # [unix or win64]
  - 14                         # [linux]
cuda_compiler_version:
  - None
```